{{ if .Values.gateway.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "gwx-app.fullname" . }}-{{ .Values.currentEnv}}-gateway
  namespace: {{ .Values.namespace }}
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
          {{- range .Values.gateway_data}}
    - {{.hosts -}}
          {{end -}}
{{ end }}