apiVersion: v1
kind: Service
metadata:
  name: {{ include "gwx-app.fullname" . }}-{{ .Values.currentEnv}}-svc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "gwx-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "gwx-app.selectorLabels" . | nindent 4 }}
